"""
baseline: fixed-time signal control (whatever netconvert generated by default,
typically 31s NS green + 31s EW green + yellows).
runs sumo headless, logs avg wait time and throughput per second.
"""
import json
from pathlib import Path
import traci

import os
NETWORK_NAME = os.environ.get("NETWORK", "network")   # "network" or "network_real"
NETWORK_DIR = Path(__file__).parent / NETWORK_NAME
SUMOCFG = NETWORK_DIR / "simulation.sumocfg"
SUFFIX = "" if NETWORK_NAME == "network" else f"_{NETWORK_NAME.replace('network_', '')}"
OUTPUT_LOG = Path(__file__).parent / f"fixed_log{SUFFIX}.json"

def main():
    tripinfo = Path(__file__).parent / f"fixed_tripinfo{SUFFIX}.xml"
    sumo_cmd = [
        "sumo", "-c", str(SUMOCFG),
        "--no-warnings", "true",
        "--tripinfo-output", str(tripinfo),
    ]
    traci.start(sumo_cmd)

    timeline = []   # per-second snapshot
    total_wait = 0.0
    total_vehicles_seen = set()
    arrived = 0

    step = 0
    while traci.simulation.getMinExpectedNumber() > 0:
        traci.simulationStep()
        step += 1

        # vehicles currently in sim
        vehs = traci.vehicle.getIDList()
        for v in vehs:
            total_vehicles_seen.add(v)

        # accumulated waiting time per vehicle (waiting = nearly stopped)
        sec_wait = sum(traci.vehicle.getWaitingTime(v) for v in vehs)
        # total queue across all edges in the network (halting = speed < 0.1 m/s)
        queue_total = sum(
            traci.edge.getLastStepHaltingNumber(e)
            for e in traci.edge.getIDList()
            if not e.startswith(":")  # skip internal junction edges
        )
        queue = {"total": queue_total}
        arrived += traci.simulation.getArrivedNumber()

        timeline.append({
            "t": step,
            "active": len(vehs),
            "arrived_cum": arrived,
            "queue": queue,
            "queue_total": sum(queue.values()),
        })

    # final avg wait: sum of accumulated waits over all vehicles that arrived
    # we use traci.simulation.getStatistics()-style; simpler: read tripinfo via sumo output
    # easier path: use sumo's --tripinfo-output. let's redo with that to get clean numbers.
    traci.close()

    # quick summary from timeline
    avg_active = sum(t["active"] for t in timeline) / max(len(timeline), 1)
    avg_queue = sum(t["queue_total"] for t in timeline) / max(len(timeline), 1)

    summary = {
        "controller": "fixed",
        "duration_sec": step,
        "unique_vehicles_seen": len(total_vehicles_seen),
        "vehicles_arrived": arrived,
        "avg_active_vehicles": round(avg_active, 2),
        "avg_total_queue": round(avg_queue, 2),
    }

    # parse tripinfo for accurate per-vehicle wait time
    import xml.etree.ElementTree as ET
    waits = []
    travels = []
    tree = ET.parse(tripinfo)
    for trip in tree.getroot().findall("tripinfo"):
        waits.append(float(trip.get("waitingTime")))
        travels.append(float(trip.get("duration")))
    avg_wait = sum(waits) / max(len(waits), 1)
    avg_travel = sum(travels) / max(len(travels), 1)
    summary["avg_wait_time_sec"] = round(avg_wait, 2)
    summary["avg_travel_time_sec"] = round(avg_travel, 2)
    summary["completed_trips"] = len(waits)

    OUTPUT_LOG.write_text(json.dumps({"summary": summary, "timeline": timeline}, indent=2))
    print(json.dumps(summary, indent=2))
    print(f"saved: {OUTPUT_LOG}")

if __name__ == "__main__":
    main()